name: Build PDF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Pandoc and LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive texlive-xetex

    - name: Download Eisvogel template
      run: |
        wget https://github.com/Wandmalfarbe/pandoc-latex-template/releases/download/v2.0.0/Eisvogel-2.0.0.tar.gz
        tar -xzf Eisvogel-2.0.0.tar.gz
        sudo mv eisvogel.latex /usr/share/pandoc/data/templates/eisvogel.tex

    - name: Compile PDF
      run: |
        pandoc --template eisvogel.tex --pdf-engine=xelatex -o output.pdf **/*.md

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: pdf
        path: output.pdf